/**
 * Shared asset catalog for generation + placeholders.
 * Kept as plain JS so both Node scripts and the Vite app can share IDs via manifest.
 */

export const STYLE_FOUNDATION =
  "Original 16-bit fantasy JRPG pixel art for a browser game, compact readable silhouette, limited cohesive color palette, crisp hard pixel edges, no anti-aliasing, no text, no watermark, designed to remain readable at small gameplay size, original character and costume design";

/** @typedef {'transparent' | 'opaque'} BgMode */

/**
 * @typedef {object} AssetSpec
 * @property {string} id
 * @property {string} purpose
 * @property {number} width
 * @property {number} height
 * @property {BgMode} background
 * @property {string} prompt
 * @property {string} publicPath
 * @property {boolean} [skipByDefault]
 */

/** @type {AssetSpec[]} */
export const ASSET_SPECS = [
  {
    id: "battle-screen-ref",
    purpose: "Empty battle-screen environment backdrop (no characters)",
    width: 512,
    height: 288,
    background: "opaque",
    publicPath: "assets/refs/battle-screen-ref.png",
    prompt: `Original 16-bit fantasy JRPG pixel art for a browser game, late-SNES-era visual language, side-view empty battle arena backdrop only, layered dusk sky distant forested hills midground ruined stone pillars and grassy ground plane, open staging areas on left and right for sprites, limited cohesive fantasy teal-and-earth palette, crisp hard pixel edges, no anti-aliasing, no text, no watermark, no UI, absolutely no characters, no people, no heroes, no enemies, no creatures, no monsters, no silhouettes of fighters, empty scenic battlefield environment only`,
  },
  {
    id: "splash-bg",
    purpose: "Title splash / menu backdrop with party lineup",
    width: 1024,
    height: 768,
    background: "opaque",
    publicPath: "assets/splash/splash-bg.png",
    skipByDefault: true,
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art title splash backdrop, dusk sky and ruined plaza, four hero party silhouettes staged as a poster lineup, no UI text, no watermark, readable title-safe composition`,
  },
  {
    id: "splash-match3",
    purpose: "Post-load splash with elemental gem ritual altar",
    width: 1024,
    height: 768,
    background: "opaque",
    publicPath: "assets/splash/splash-match3.png",
    skipByDefault: true,
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art splash backdrop, stone ritual altar with four large elemental match-3 gems as focal point (red flame, blue ice, green leaf, yellow light), dusk sky title-safe upper third, no characters, no UI text, no watermark`,
  },
  {
    id: "hero-warrior",
    purpose: "Red warrior battle sprite",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/heroes/hero-warrior.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a sturdy red-aligned warrior, three-quarter side view facing right, short sword and small round shield, broad readable silhouette, practical original armor with red cloth accents, confident neutral combat stance, limited cohesive palette, designed for a 64x64 gameplay sprite.`,
  },
  {
    id: "hero-mage",
    purpose: "Blue mage battle sprite",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/heroes/hero-mage.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a blue-aligned mage, side view facing right, lightweight layered robe, short staff with a simple ice crystal, intelligent restrained design, clear silhouette distinct from the warrior, limited blue and neutral palette, designed for a 64x64 gameplay sprite.`,
  },
  {
    id: "hero-ranger",
    purpose: "Green ranger battle sprite",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/heroes/hero-ranger.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a green-aligned ranger, side view facing right, compact bow, asymmetrical travel cloak, agile combat stance, readable silhouette at small scale, original fantasy costume, limited green and earthy palette, designed for a 64x64 gameplay sprite.`,
  },
  {
    id: "hero-priest",
    purpose: "Yellow priest battle sprite",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/heroes/hero-priest.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a yellow-aligned healer priest, side view facing right, small ceremonial staff, warm layered garments, calm supportive pose, distinctive readable silhouette, original fantasy design, limited gold cream and brown palette, designed for a 64x64 gameplay sprite.`,
  },
  {
    id: "enemy-slime",
    purpose: "Normal enemy slime",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/enemies/enemy-slime.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a small slime enemy, side view facing left, blob body with simple eyes, readable silhouette at 64x64, limited teal and purple palette, crisp hard pixel edges, no text, no watermark.`,
  },
  {
    id: "enemy-bat",
    purpose: "Normal enemy bat",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/enemies/enemy-bat.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a winged bat enemy (летучая мышь), side view facing left, compact body with membrane wings, same silhouette clarity and limited palette discipline as the slime and wraith enemies, brown magenta and soft violet accents, crisp hard pixel edges, no text, no watermark.`,
  },
  {
    id: "enemy-wraith",
    purpose: "Chapter 2 yellow wraith enemy",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/enemies/enemy-wraith.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art battle sprite of a ghostly yellow-aligned wraith, side view facing left, hooded spirit with trailing mist, readable silhouette at 64x64, limited gold cream and violet palette, crisp hard pixel edges, no text, no watermark.`,
  },
  {
    id: "boss-goblin",
    purpose: "Goblin chieftain boss",
    width: 128,
    height: 128,
    background: "transparent",
    publicPath: "assets/enemies/boss-goblin.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. Original 16-bit fantasy JRPG pixel-art boss sprite of a goblin chieftain warlord, side view facing left, bulky patched plate armor, oversized cleaver, intimidating silhouette matching the party hero art style, limited earthy greens browns and one ember accent, crisp hard pixel edges, designed for a 128x128 boss sprite, no text, no watermark.`,
  },
  {
    id: "env-hollow-keep",
    purpose: "Empty hollow keep ending arena backdrop",
    width: 960,
    height: 720,
    background: "opaque",
    publicPath: "assets/env/env-hollow-keep.png",
    skipByDefault: true,
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art side-view empty castle throne hall, cracked stone floor, cold cyan and violet moonlight through broken stained glass, abandoned banners, open staging areas left and right, deeply unsettling lonely atmosphere, absolutely no characters no people no heroes no enemies, empty scenic environment only, no text, no watermark, no UI.`,
  },
  {
    id: "ending-party",
    purpose: "Final ending art of the four heroes",
    width: 1024,
    height: 768,
    background: "opaque",
    publicPath: "assets/splash/ending-party.png",
    skipByDefault: true,
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art ending poster of four heroes standing together in an empty moonlit castle hall looking confused and defiant, warrior mage ranger priest lineup matching existing party designs, cold cyan violet lighting, title-safe composition, no UI text, no watermark.`,
  },
  {
    id: "gems-set",
    purpose: "Four match-3 elemental gems sheet",
    width: 128,
    height: 128,
    background: "transparent",
    publicPath: "assets/gems/gems-set.png",
    prompt: `${STYLE_FOUNDATION}, transparent background where applicable. A cohesive set of four original 16-bit pixel-art match-3 elemental gems arranged in a 2x2 grid: red flame, blue ice, green leaf and yellow light, each with a clearly different silhouette rather than color alone, high readability at small size, limited palette, crisp hard pixel edges, no letters, no text, no watermark.`,
  },
  {
    id: "env-worldmap",
    purpose: "World-map environment sample",
    width: 256,
    height: 144,
    background: "opaque",
    publicPath: "assets/env/env-worldmap.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art world map environment, top-down slight isometric, serpentine dirt road left-right zigzags across quiet grass fields, sparse tree clumps only at far edges, one small village near LEFT, one cave mouth mid-right, one stone fortress mid-right, foggy marsh and ruined bridge in the LOWER band, ominous distant keep silhouette far RIGHT, broad empty grassy quiet zones for UI markers, limited green earth and sky palette, modular tileset feel, no text, no watermark, no UI, readable landmarks only.`,
  },
  {
    id: "env-village",
    purpose: "Village hub environment with three facility zones",
    width: 512,
    height: 288,
    background: "opaque",
    publicPath: "assets/env/env-village.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art village hub side-view background, warm cobblestone plaza, three readable building zones left-to-right: a stone mine entrance with timber supports and ore carts, an open training yard with wooden dummies and sparring posts, a workshop shed with forge glow and hanging tools, soft afternoon sky, limited warm earth and soft sky palette, empty of player characters, no text, no watermark, no UI.`,
  },
  {
    id: "battle-boss-bg",
    purpose: "Empty goblin fortress boss arena backdrop (no characters)",
    width: 512,
    height: 288,
    background: "opaque",
    publicPath: "assets/env/battle-boss-bg.png",
    prompt: `Original 16-bit fantasy JRPG pixel art for a browser game, late-SNES-era visual language, side-view empty boss arena inside a dark goblin fortress, torchlit stone hall, cracked floor, ominous red-amber lighting, open staging areas on left and right for sprites, limited dark earthy palette with ember accents, crisp hard pixel edges, no anti-aliasing, no text, no watermark, no UI, absolutely no characters, no people, no heroes, no enemies, no creatures, no monsters, empty scenic battlefield environment only`,
  },
  {
    id: "icon-gold",
    purpose: "Gold coin currency icon",
    width: 48,
    height: 48,
    background: "transparent",
    publicPath: "assets/ui/icon-gold.png",
    prompt: `${STYLE_FOUNDATION}, transparent background. Single original 16-bit pixel-art gold coin icon, round coin with simple embossed crest, warm gold yellow palette, crisp hard edges, high readability at 32px, no text, no letters, no watermark.`,
  },
  {
    id: "icon-materials",
    purpose: "Materials crate currency icon",
    width: 48,
    height: 48,
    background: "transparent",
    publicPath: "assets/ui/icon-materials.png",
    prompt: `${STYLE_FOUNDATION}, transparent background. Single original 16-bit pixel-art wooden supply crate icon with metal bands and a small ore chunk on top, earthy brown and grey palette, crisp hard edges, high readability at 32px, no text, no watermark.`,
  },
  {
    id: "facility-mine",
    purpose: "Village Mine facility icon",
    width: 96,
    height: 96,
    background: "transparent",
    publicPath: "assets/ui/facility-mine.png",
    prompt: `${STYLE_FOUNDATION}, transparent background. Original 16-bit pixel-art village Mine building icon, stone tunnel entrance with timber supports and a small ore cart, readable silhouette, limited grey brown palette, no characters, no text, no watermark.`,
  },
  {
    id: "facility-training",
    purpose: "Village Training Ground facility icon",
    width: 96,
    height: 96,
    background: "transparent",
    publicPath: "assets/ui/facility-training.png",
    prompt: `${STYLE_FOUNDATION}, transparent background. Original 16-bit pixel-art Training Ground facility icon, wooden sparring posts and a practice dummy on packed earth, readable silhouette, warm wood palette, no characters, no text, no watermark.`,
  },
  {
    id: "facility-workshop",
    purpose: "Village Workshop facility icon",
    width: 96,
    height: 96,
    background: "transparent",
    publicPath: "assets/ui/facility-workshop.png",
    prompt: `${STYLE_FOUNDATION}, transparent background. Original 16-bit pixel-art Workshop forge shed icon, anvil bellows and warm forge glow, readable silhouette, brown and ember palette, no characters, no text, no watermark.`,
  },
  {
    id: "icon-warriors",
    purpose: "Party warriors training icon",
    width: 64,
    height: 64,
    background: "transparent",
    publicPath: "assets/ui/icon-warriors.png",
    prompt: `${STYLE_FOUNDATION}, transparent background. Original 16-bit pixel-art icon of two small fantasy warrior silhouettes standing ready with simple weapons, compact party emblem feel, limited red and steel palette, readable at small size, no faces detail required, no text, no watermark.`,
  },
  // —— Mobile portrait variants (420×760 full-bleed; battle field strip 420×240) ——
  {
    id: "splash-bg-mobile",
    purpose: "Portrait title splash / menu backdrop with party lineup",
    width: 420,
    height: 760,
    background: "opaque",
    publicPath: "assets/splash/splash-bg-mobile.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art PORTRAIT title splash (tall 9:16 phone screen), dusk sky and ruined plaza, four hero party silhouettes staged in the LOWER 55% as a vertical poster lineup, large empty title-safe sky in the UPPER third, no UI text, no watermark, composed for 420x760`,
  },
  {
    id: "splash-match3-mobile",
    purpose: "Portrait post-load splash with elemental gem ritual altar",
    width: 420,
    height: 760,
    background: "opaque",
    publicPath: "assets/splash/splash-match3-mobile.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art PORTRAIT splash (tall phone), stone ritual altar with four large elemental match-3 gems centered mid-frame (red flame, blue ice, green leaf, yellow light), dusk sky title-safe upper third, no characters, no UI text, no watermark, composed for 420x760`,
  },
  {
    id: "env-worldmap-mobile",
    purpose: "Portrait world-map with vertical path layout",
    width: 420,
    height: 760,
    background: "opaque",
    publicPath: "assets/env/env-worldmap-mobile.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art PORTRAIT world map (tall phone 420x760), top-down slight isometric SERPENTINE progression path: village near TOP-CENTER, path zigzags LEFT then RIGHT down through quiet grass, forest edge, quarry, cave mid-right, GOBLIN FORTRESS mid-center as chapter-1 climax, then a clear terrain transition (river fog or stone gate band), then marsh LEFT, ruined bridge RIGHT, watchtower lower-left, ominous HOLLOW KEEP bottom-right finale. Broad quiet grassy fields behind UI, sparse trees only at edges, ONE cave landmark, ONE fortress, ONE marsh/bridge, ONE final keep. Road painted to match vertical serpentine. Limited green earth sky palette, modular tileset feel, no text, no watermark, no UI, composed for 420x760`,
  },
  {
    id: "env-village-mobile",
    purpose: "Portrait village hub with vertical facility zones",
    width: 420,
    height: 760,
    background: "opaque",
    publicPath: "assets/env/env-village-mobile.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art PORTRAIT village hub (tall phone), warm cobblestone plaza, three readable building zones stacked TOP-TO-BOTTOM: stone mine entrance with timber supports, open training yard with wooden dummies, workshop shed with forge glow, soft afternoon sky at top, limited warm earth palette, empty of player characters, no text, no watermark, no UI, composed for 420x760`,
  },
  {
    id: "env-hollow-keep-mobile",
    purpose: "Portrait hollow keep ending arena backdrop",
    width: 420,
    height: 760,
    background: "opaque",
    publicPath: "assets/env/env-hollow-keep-mobile.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art PORTRAIT empty castle throne hall (tall phone), tall cracked stone columns, cold cyan and violet moonlight through broken stained glass, abandoned banners, open center staging, deeply unsettling lonely atmosphere, absolutely no characters, empty scenic environment only, no text, no watermark, no UI, composed for 420x760`,
  },
  {
    id: "ending-party-mobile",
    purpose: "Portrait ending art of the four heroes",
    width: 420,
    height: 760,
    background: "opaque",
    publicPath: "assets/splash/ending-party-mobile.png",
    prompt: `${STYLE_FOUNDATION}. Original 16-bit fantasy JRPG pixel-art PORTRAIT ending poster (tall phone), four heroes standing together in an empty moonlit castle hall looking confused and defiant, warrior mage ranger priest vertical-friendly lineup matching existing party designs, cold cyan violet lighting, title-safe upper sky, no UI text, no watermark, composed for 420x760`,
  },
  {
    id: "battle-screen-ref-mobile",
    purpose: "Portrait battle field strip backdrop (top enemy band)",
    width: 420,
    height: 240,
    background: "opaque",
    publicPath: "assets/refs/battle-screen-ref-mobile.png",
    prompt: `Original 16-bit fantasy JRPG pixel art for a browser game, late-SNES-era visual language, WIDE SHORT empty battle arena strip for mobile (420x240), layered dusk sky, distant forested hills, grassy ground along the BOTTOM edge, open enemy staging across the UPPER-CENTER, limited cohesive fantasy teal-and-earth palette, crisp hard pixel edges, no anti-aliasing, no text, no watermark, no UI, absolutely no characters, empty scenic battlefield environment only`,
  },
  {
    id: "battle-boss-bg-mobile",
    purpose: "Portrait boss field strip backdrop (top enemy band)",
    width: 420,
    height: 240,
    background: "opaque",
    publicPath: "assets/env/battle-boss-bg-mobile.png",
    prompt: `Original 16-bit fantasy JRPG pixel art for a browser game, late-SNES-era visual language, WIDE SHORT empty boss arena strip for mobile (420x240), dark goblin fortress hall, torchlit stone, cracked floor along bottom, ominous red-amber lighting, open enemy staging across UPPER-CENTER, limited dark earthy palette with ember accents, crisp hard pixel edges, no anti-aliasing, no text, no watermark, no UI, absolutely no characters, empty scenic battlefield environment only`,
  },
];

export const GEM_IDS = ["gem-flame", "gem-ice", "gem-leaf", "gem-light"];
